In [1]:
import numpy
import numpy as np
import pandas as pd
import sys, glob
import urllib3
import h5py
import cdsapi, zipfile, os, time
import warnings
import shutil
import xarray
from datetime import date
warnings.filterwarnings('ignore')
import pycountry
sys.path.append(os.getcwd()+'/../cds-backend/code/')
import cds_eua3 as eua
# import numbaprocess
import copy
import glob
from numba import njit
import pandas
import glob
import pickle
import matplotlib

In [2]:
def request(rqdict, source, remove_file=True):
    t0 = time.time()

    c = cdsapi.Client()
    r = c.retrieve(
        source,rqdict)
    print('Request took: ' + str(time.time() - t0) + ' seconds')
    if True:
        r.download(target='download.zip')
        assert os.stat('download.zip').st_size == r.content_length, "Downloaded file is incomplete"
    z = zipfile.ZipFile('download.zip')
    z.extractall(path='./download/')
    z.close()
    
    
    files = glob.glob('./download/*.nc')
    data=eua.CDMDataset(files[0])
    os.remove('download.zip')
    if remove_file:
        try:
           shutil.rmtree('./download/')
        except:
           print('Error while deleting directory')

    return data

In [3]:
cuon = 'insitu-comprehensive-upper-air-observation-network'

In [ ]:
out = request({ 'variable':'air_temperature','gridded': [-90,-178,89,178],'date': ['20100101', '20100401']},cuon, remove_file=True)
display(out)
# out = request({ 'variable':['temperature'],'gridded': [-90,-180,90,178],'date': ['20100101', '20100501']},cuon, remove_file=True)
# display(out)

In [10]:
out = request({ 'variable':['temperature'],'gridded': [-90,-178,89,178],'date': ['20100101', '20100401']},cuon, remove_file=True)
display(out)
# out = request({ 'variable':['temperature'],'gridded': [-90,-180,90,178],'date': ['20100101', '20100501']},cuon, remove_file=True)
# display(out)

2021-03-05 09:24:02,688 INFO Welcome to the CDS
2021-03-05 09:24:02,689 INFO Sending request to https://sis-dev.climate.copernicus.eu/api/v2/resources/insitu-comprehensive-upper-air-observation-network
2021-03-05 09:24:02,902 INFO Request is queued
2021-03-05 09:24:03,943 INFO Request is running
2021-03-05 09:24:05,481 INFO Request is completed
2021-03-05 09:24:05,483 INFO Downloading http://136.156.132.176/cache-compute-0002/cache/data2/adaptor.comprehensive_upper_air.retrieve-1614932644.8077047-4805-4-221e2e3a-7033-4574-9402-f8529ee3409d.zip to download.zip (984.7K)
2021-03-05 09:24:05,682 INFO Download rate 4.8M/s 


Request took: 2.8261518478393555 seconds
2021-03-05 09:24:05,694 - upperair.cdm | __init__ - DEBUG - [OPEN] ./download/dest_gridded_temperature.nc


2021-03-05 09:24:05,694 DEBUG [OPEN] ./download/dest_gridded_temperature.nc


File: <HDF5 file "dest_gridded_temperature.nc" (mode r)>
Filename: ./download/dest_gridded_temperature.nc
(G)roups/(V)ariables: 

 - V | hour_________________________________________ : : (2,)
 - V | lat__________________________________________ : : (8,)
 - V | lon__________________________________________ : : (5,)
 - V | pressure_____________________________________ : : (16,)
 - V | ta_anomaly___________________________________ : : (8, 5, 2, 16, 1)
 - V | ta_average___________________________________ : : (8, 5, 2, 16, 1)
 - V | time_________________________________________ : : (1,)

In [6]:
out['hour'][:]

array([12])

In [11]:
out = request({ 'variable':['temperature'],'gridded': [0,0,85,45],'date': ['20100101', '20100201'], 'time': [12], 'pressure_level':500},cuon, remove_file=False)
display(out)

2021-03-05 09:24:25,385 INFO Welcome to the CDS
2021-03-05 09:24:25,386 INFO Sending request to https://sis-dev.climate.copernicus.eu/api/v2/resources/insitu-comprehensive-upper-air-observation-network
2021-03-05 09:24:25,449 INFO Request is queued
2021-03-05 09:24:26,487 INFO Request is running
2021-03-05 09:24:28,025 INFO Request is completed
2021-03-05 09:24:28,027 INFO Downloading http://136.156.132.176/cache-compute-0002/cache/data1/adaptor.comprehensive_upper_air.retrieve-1614932667.2725704-4833-5-adf77ed0-537f-48c3-aacd-1ad2038ba14d.zip to download.zip (12.6K)
2021-03-05 09:24:28,090 INFO Download rate 201.8K/s


Request took: 2.67421817779541 seconds
2021-03-05 09:24:28,098 - upperair.cdm | __init__ - DEBUG - [OPEN] ./download/dest_gridded_temperature.nc


2021-03-05 09:24:28,098 DEBUG [OPEN] ./download/dest_gridded_temperature.nc


File: <HDF5 file "dest_gridded_temperature.nc" (mode r)>
Filename: ./download/dest_gridded_temperature.nc
(G)roups/(V)ariables: 

 - V | hour_________________________________________ : : (1,)
 - V | lat__________________________________________ : : (9,)
 - V | lon__________________________________________ : : (5,)
 - V | pressure_____________________________________ : : (1,)
 - V | ta_anomaly___________________________________ : : (9, 5, 1, 1, 1)
 - V | ta_average___________________________________ : : (9, 5, 1, 1, 1)
 - V | time_________________________________________ : : (1,)

In [13]:
out['pressure'][:]

array([50000])

In [14]:
out['hour'][:]

array([12])

In [12]:
out['ta_anomaly'][:]

array([[[[[        nan]]],


        [[[        nan]]],


        [[[        nan]]],


        [[[        nan]]],


        [[[        nan]]]],



       [[[[ 0.91221619]]],


        [[[        nan]]],


        [[[        nan]]],


        [[[        nan]]],


        [[[        nan]]]],



       [[[[ 2.23127747]]],


        [[[        nan]]],


        [[[        nan]]],


        [[[        nan]]],


        [[[ 1.68208313]]]],



       [[[[ 0.29643759]]],


        [[[-0.45889282]]],


        [[[        nan]]],


        [[[ 2.01115727]]],


        [[[ 3.26075745]]]],



       [[[[        nan]]],


        [[[        nan]]],


        [[[-1.26494217]]],


        [[[ 0.16860962]]],


        [[[ 1.26411438]]]],



       [[[[        nan]]],


        [[[        nan]]],


        [[[-2.60171509]]],


        [[[-1.32324076]]],


        [[[ 0.08779907]]]],



       [[[[-1.29992676]]],


        [[[-0.94068146]]],


        [[[        nan]]],


        [[[-0.078125  ]]],


  