# Check sensor id from era5fb data 




In [2]:
import h5py as h5
import pandas as pd
import numpy as np




In [6]:
f = '/scratch/das/federico/HARVEST_YEARLY_10NOV2023_Vienna_Lin_Bethel/era5_1/0-20001-0-11035/0-20001-0-11035_2014_era5_1_harvested_era5.conv.??????.11035.txt.gz.nc'

print( np.unique ( h5.File(f, 'r')['era5fb']['sonde_type@conv'][:] ) ) 

[71. 79. 80.]


In [7]:
print( np.unique ( h5.File(f.replace('2014', '2015'), 'r')['era5fb']['sonde_type@conv'][:] ) ) 

[ 71.  80. 177.]


In [8]:
print( np.unique ( h5.File(f.replace('2014', '2022'), 'r')['era5fb']['sonde_type@conv'][:] ) ) 

[141. 163.]


In [7]:
f = '/scratch/das/federico/MERGED_YEARLY_16NOV_checkBUFR_sensor/0-20001-0-10393/0-20001-0-10393_2013_CEUAS_merged_v3.nc'
print( np.unique ( h5.File(f, 'r')['era5fb']['sonde_type@conv'][:] , return_counts = True )  )


(array([-2.1474836e+09,  8.0000000e+01], dtype=float32), array([229488, 687877]))


In [3]:
f = '/scratch/das/federico/MERGED_YEARLY_16NOV_checkBUFR/0-20001-0-11035/0-20001-0-11035_2018_CEUAS_merged_v3.nc' 

keys =  h5.File(f, 'r')['era5fb'].keys()

In [5]:
df = {}

for k in keys:
    df[k] =  h5.File(f, 'r')['era5fb'][k][:10000]
    print( k , '  ' ,  h5.File(f, 'r')['era5fb'][k][:3])
    
df = pd.DataFrame.from_dict(df)




albedo@modsurf    [-2.1474836e+09 -2.1474836e+09 -2.1474836e+09]
an_depar@body    [-2.1474836e+09 -2.1474836e+09 -2.1474836e+09]
an_depar@surfbody_feedback    [-2.1474836e+09 -2.1474836e+09 -2.1474836e+09]
an_sens_obs@body    [-2.1474836e+09 -2.1474836e+09 -2.1474836e+09]
andate    [-2147483648 -2147483648 -2147483648]
antime    [-2147483648 -2147483648 -2147483648]
biascorr@body    [-2.1474836e+09 -2.1474836e+09 -2.1474836e+09]
biascorr_fg@body    [-2.1474836e+09 -2.1474836e+09 -2.1474836e+09]
bufrtype@hdr    [-2147483648 -2147483648 -2147483648]
class    [-2147483648 -2147483648 -2147483648]
codetype@hdr    [-2147483648 -2147483648 -2147483648]
collection_identifier@conv    [-2147483648 -2147483648 -2147483648]
date@hdr    [-2147483648 -2147483648 -2147483648]
datum_sfc_event@surfbody_feedback    [-2147483648 -2147483648 -2147483648]
datum_status@body    [-2147483648 -2147483648 -2147483648]
datum_status@surfbody_feedback    [-2147483648 -2147483648 -2147483648]
eda_spread@errstat   

ValueError: Per-column arrays must each be 1-dimensional